apiVersion: v2
name: vcluster-k3s
version: 1.0.0
description: This Chart deploys vcluster-k3s.
#vcluster use default k3s
dependencies:
  - name: vcluster
    version: 0.14.*
    repository: https://charts.loft.sh
